### ISSUE TITLE
confusing warning/error

### ISSUE THREAD

**Issue by tdhock** [rkillick/changepoint#45]
hi @rkillick I'm using changepoint in my teaching https://github.com/tdhock/cs499-599-fall-2020/blob/master/homeworks/8.org
I recommended my students use the code
```r
changepoint::cpt.mean(logratio_vector, Q=100, method=”BinSeg”, penalty=”Manual”)
```
and one student was wondering if it is normal to see a lot of warnings. For example,
```r
> fit6 <- changepoint::cpt.mean(rnorm(10), penalty="Manual", method="BinSeg", pen.value=0, Q=6)
Warning message:
In BINSEG(sumstat, pen = pen.value, cost_func = costfunc, minseglen = minseglen,  :
  The number of changepoints identified is Q, it is advised to increase Q to make sure changepoints have not been missed.
> 
```
But if I increase Q I get an error:
```r
> fit7 <- changepoint::cpt.mean(rnorm(10), penalty="Manual", method="BinSeg", pen.value=0, Q=7)
Error in BINSEG(sumstat, pen = pen.value, cost_func = costfunc, minseglen = minseglen,  : 
  Q is larger than the maximum number of segments 6
> 
```
so that brings up two questions:

- can you please remove the warning when the user specifies pen.value=0? in that case the largest model will always be returned and that is no surprise (no need to warn).
- can maximum number of segments be the number of data points? (10 instead of 6 in this example)

Thanks!
Toby

**Comment by rkillick** [comment]
Ooooooh interesting!

- _can you please remove the warning when the user specifies pen.value=0? in that case the largest model will always be returned and that is no surprise (no need to warn)._

Yes, I agree that this is a special case that isn't currently considered separately.

- _can maximum number of segments be the number of data points? (10 instead of 6 in this example)_
Thanks for spotting this.  The check was hardcoded in the BINSEG function as n/2+1 whereas it should be n/minseglen+1.

**Comment by rkillick** [comment]
Done in the github version.  Not pushed to CRAN yet as i'm doing final tests on the cpt.reg function before the next release.

**Comment by tdhock** [comment]
great thanks for the quick response Rebecca!
